name: Rust

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  rustfmt_and_clippy:
    name: Rustfmt and Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Nightly with rustfmt and clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2.7.3

      - name: "Check formatting"
        run: cargo +nightly fmt --check --all

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

  build_and_test:
    name: "Build and Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2.7.3

      - name: Cargo update
        run: cargo update

      - name: "Build"
        run: cargo build

      - name: "Test"
        # Run all tests (bins, examples, lib, integration and docs)
        # https://doc.rust-lang.org/cargo/commands/cargo-test.html#target-selection
        run: cargo test

      - name: "Check documentation"
        # env:
        #   RUSTDOCFLAGS: -D warnings
        run: cargo doc --no-deps --workspace --lib --document-private-items --examples

  miri:
    if: ( ! github.event.pull_request.draft )
    name: "Test with Miri"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust nightly with Miri
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: miri
          targets: x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu
      
      - uses: Swatinem/rust-cache@v2.7.3

      - name: Cargo version
        run: cargo version --verbose

      - name: Cargo update
        run: cargo update
      
      - name: Test with Miri on x86_64
        run: cargo miri test -p clmul -p matrix-transpose --target x86_64-unknown-linux-gnu
      
      - name: Test with Miri on aarch64
        run: cargo miri test -p clmul -p matrix-transpose --target aarch64-unknown-linux-gnu
